default_config:

homeassistant:
  name: !secret homeassistant_name
  latitude: !secret zones_home_latitude
  longitude: !secret zones_home_longitude
  elevation: !secret zones_home_elevation
  time_zone: "Europe/Madrid"
  unit_system: metric
  external_url: !secret homeassistant_external_url
  internal_url: !secret homeassistant_internal_url
  customize: !include customize.yaml
  packages: !include_dir_named packages

group: !include groups.yaml
automation: !include automations.yaml
alexa:
  smart_home:
api:
script: !include scripts.yaml
scene: !include scenes.yaml
wake_on_lan:
zone: !include zones.yaml

sensor:
  - platform: time_date
    display_options:
      - "time_utc"
      - "time"
