default_config:

homeassistant:
  customize: !include customize.yaml

http:
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

lovelace:
  mode: yaml

weather:
  - platform: openweathermap
    name: home
    api_key: !secret weather_openweathermap_api_key

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_bot_chat_id

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot

  - platform: miflora
    mac: !secret living_room_mi_flora_01_mac
    name: Living Room Mi Flora 01
    force_update: true # Fix problems with graphic spikes
    median: 3 # Fix problems with graphic spikes
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery

plant:
  # Orchidaceae, Phalaenopsis
  living_room_orchid:
    sensors:
      moisture: sensor.living_room_mi_flora_01_moisture
      battery: sensor.living_room_mi_flora_01_battery
      temperature: sensor.living_room_mi_flora_01_temperature
      conductivity: sensor.living_room_mi_flora_01_conductivity
      brightness: sensor.living_room_mi_flora_01_light_intensity
    min_moisture: 15
    max_moisture: 65
    min_battery: 20
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 15
    max_temperature: 32
    min_brightness: 2000
    max_brightness: 30000
    check_days: 3

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: !secret tuya_country_code
  platform: smart_life

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml